---
title: "R Notebook"
output: html
---


```{r}
library(tidyverse)
library(rjson)
library(ggthemes)
library(plotly)

source('load_data.R')

library(tidyverse)
library(sf)
library(leaflet)
library(rgdal)
# install.packages("mapview", dependencies = TRUE)
# library(mapview)
can_prov <- readOGR(dsn = "./data/raw/lcma000b16a_e/lcma000b16a_e.shp")
can_cma <- readOGR(dsn = "./data/raw/lcma000b16a_e/lcma000b16a_e.shp")
can <- spTransform(can_prov, CRS("+proj=longlat +datum=WGS84"))
fake_cma <- read_csv('./data/raw/fake_cma.csv')
```

```{r}

labels <- 
  can@data %>% 
  mutate(label = paste0("<strong>", CMANAME, "</strong><br/><strong>ID: ", CMAUID, "</strong>")) %>% 
  pull(label) %>% 
  lapply(htmltools::HTML)

values <- 
  fake_cma %>%
  mutate(cmapuid = as.character(cmapuid)) %>% 
  filter(year == 2019) %>%
  right_join(can@data, by = c('cmapuid' = 'CMAPUID')) %>%
  pull(value)


bins <- c(0, 10, 20, 50, 100, 200, 500, 1000, Inf)
pal <- colorBin("YlOrRd", domain = c(0, max(fake_cma$value %>% max())), bins = bins)

# can$value <- values

leaflet() %>%
  addTiles() %>%
  setView(-95, 55, zoom = 5) %>%
  addPolygons(
    data = can,
    fillColor = ~pal(values),
    weight = 0,
    fillOpacity = 0.7,
    label = labels,
    highlight = highlightOptions(
      weight = 1,
      bringToFront = TRUE)
  )
```

